; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --version 6
; Tests for the SimpleDCE pass (-passes=simple-dce). Each section covers one
; of the transformations described in DCE-Doc.md.
;
; RUN: opt -passes=simple-dce -S < %s | FileCheck %s
; Running the pass a second time must not change anything.
; RUN: opt -passes=simple-dce,simple-dce -S < %s | FileCheck %s

declare void @unknown(i32)
declare void @use(ptr)
declare i32 @pure(i32) memory(none) nounwind willreturn
declare i32 @may_not_return(i32) memory(none) nounwind

;===----------------------------------------------------------------------===;
; 1. Trivially dead instruction elimination
;===----------------------------------------------------------------------===;

; Example 1 from the requirements. %add only becomes unused once %mul is
; removed; both are removed in one run.
define dso_local i32 @dead_instructions(i32 %argc, ptr %argv) {
; CHECK-LABEL: define dso_local i32 @dead_instructions(
; CHECK-SAME: i32 [[ARGC:%.*]], ptr [[ARGV:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret i32 0
;
entry:
  %add = add nsw i32 %argc, 42
  %mul = mul nsw i32 %add, 2
  ret i32 0
}

; Instructions with side effects are kept even though their results are
; unused, and so is everything that computes their operands: memory writes,
; volatile and atomic accesses, calls to unknown functions, and calls that do
; not touch memory but may not return.
define void @side_effects_are_kept(ptr %p, i32 %x) {
; CHECK-LABEL: define void @side_effects_are_kept(
; CHECK-SAME: ptr [[P:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V:%.*]] = add i32 [[X]], 1
; CHECK-NEXT:    store i32 [[V]], ptr [[P]], align 4
; CHECK-NEXT:    [[VOL:%.*]] = load volatile i32, ptr [[P]], align 4
; CHECK-NEXT:    [[RMW:%.*]] = atomicrmw add ptr [[P]], i32 1 seq_cst, align 4
; CHECK-NEXT:    call void @unknown(i32 [[X]])
; CHECK-NEXT:    [[NR:%.*]] = call i32 @may_not_return(i32 [[X]])
; CHECK-NEXT:    ret void
;
entry:
  %v = add i32 %x, 1
  store i32 %v, ptr %p
  %vol = load volatile i32, ptr %p
  %rmw = atomicrmw add ptr %p, i32 1 seq_cst
  call void @unknown(i32 %x)
  %nr = call i32 @may_not_return(i32 %x)
  ret void
}

; Unused side-effect-free instructions are removed, including plain loads and
; calls to functions that neither write memory, nor unwind, nor fail to
; return. %keep is returned, so it and its operand %base stay.
define i32 @side_effect_free_are_removed(ptr %p, i32 %x, i32 %y) {
; CHECK-LABEL: define i32 @side_effect_free_are_removed(
; CHECK-SAME: ptr [[P:%.*]], i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[BASE:%.*]] = add i32 [[X]], [[Y]]
; CHECK-NEXT:    [[KEEP:%.*]] = mul i32 [[BASE]], 5
; CHECK-NEXT:    ret i32 [[KEEP]]
;
entry:
  %ld = load i32, ptr %p
  %c = call i32 @pure(i32 %ld)
  %base = add i32 %x, %y
  %keep = mul i32 %base, 5
  %dead = sub i32 %keep, %c
  ret i32 %keep
}

; %sum and %sum.next only use each other, so neither is ever unused, but
; nothing that has to be kept depends on them. The induction variable controls
; the loop exit and is kept.
define void @dead_phi_cycle(i32 %n) {
; CHECK-LABEL: define void @dead_phi_cycle(
; CHECK-SAME: i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %sum = phi i32 [ 0, %entry ], [ %sum.next, %loop ]
  %sum.next = add i32 %sum, %i
  %i.next = add i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Lifetime markers are removed together with an alloca that has no other
; users. For %dead this is only the case after the dead %gep is removed, which
; happens in the same run. The markers of %live, which escapes, are kept.
define void @lifetime_markers() {
; CHECK-LABEL: define void @lifetime_markers() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LIVE:%.*]] = alloca i32, align 4
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[LIVE]])
; CHECK-NEXT:    call void @use(ptr [[LIVE]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[LIVE]])
; CHECK-NEXT:    ret void
;
entry:
  %dead = alloca [4 x i32]
  call void @llvm.lifetime.start.p0(ptr %dead)
  %gep = getelementptr [4 x i32], ptr %dead, i64 0, i64 1
  call void @llvm.lifetime.end.p0(ptr %dead)
  %live = alloca i32
  call void @llvm.lifetime.start.p0(ptr %live)
  call void @use(ptr %live)
  call void @llvm.lifetime.end.p0(ptr %live)
  ret void
}

; Debug records of removed instructions are rewritten in terms of the remaining
; operands (salvaged). This works through several levels (%b uses %a), even
; though the block containing the use %b is laid out before the block
; containing its operand %a.
define i32 @debug_info_salvage(i32 %x) !dbg !5 {
; CHECK-LABEL: define i32 @debug_info_salvage(
; CHECK-SAME: i32 [[X:%.*]]) !dbg [[DBG4:![0-9]+]] {
; CHECK-NEXT:  [[DEF:.*:]]
; CHECK-NEXT:      #dbg_value(i32 [[X]], [[META9:![0-9]+]], !DIExpression(DW_OP_plus_uconst, 1, DW_OP_stack_value), [[META11:![0-9]+]])
; CHECK-NEXT:      #dbg_value(i32 [[X]], [[META10:![0-9]+]], !DIExpression(DW_OP_plus_uconst, 1, DW_OP_constu, 3, DW_OP_mul, DW_OP_stack_value), [[META12:![0-9]+]])
; CHECK-NEXT:    ret i32 [[X]], !dbg [[DBG13:![0-9]+]]
;
entry:
  br label %def

use:
  %b = mul i32 %a, 3, !dbg !12
    #dbg_value(i32 %b, !10, !DIExpression(), !12)
  ret i32 %x, !dbg !13

def:
  %a = add i32 %x, 1, !dbg !11
    #dbg_value(i32 %a, !9, !DIExpression(), !11)
  br label %use
}

;===----------------------------------------------------------------------===;
; 2. Dead block elimination
;===----------------------------------------------------------------------===;

; Once %dead is removed, %block.1 only jumps to %block.2,
; so it is removed and %entry branches to %block.2 on both edges.
; That branch becomes unconditional, which makes %cmp dead, and %block.2, now
; reached only from %entry, is merged into %entry.
define i32 @dead_blocks(i32 %x) {
; CHECK-LABEL: define i32 @dead_blocks(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret i32 [[X]]
;
entry:
  %cmp = icmp sgt i32 %x, 0
  br i1 %cmp, label %block.1, label %block.2

block.1:
  %dead = add i32 %x, 1
  br label %block.2

block.2:
  ret i32 %x
}

; A conditional branch (in %left) and a switch (in %right) whose destinations
; are all the same block become unconditional branches. The PHI in %join keeps
; one entry for the remaining edge from %right, and %cmp becomes dead. %right is
; then merged into %left, whose only successor it is.
define i32 @branch_to_common_successor(i1 %c, i32 %x, i32 %y) {
; CHECK-LABEL: define i32 @branch_to_common_successor(
; CHECK-SAME: i1 [[C:%.*]], i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br i1 [[C]], label %[[LEFT:.*]], label %[[JOIN:.*]]
; CHECK:       [[LEFT]]:
; CHECK-NEXT:    call void @unknown(i32 [[X]])
; CHECK-NEXT:    call void @unknown(i32 [[Y]])
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[R:%.*]] = phi i32 [ [[X]], %[[ENTRY]] ], [ [[Y]], %[[LEFT]] ]
; CHECK-NEXT:    ret i32 [[R]]
;
entry:
  br i1 %c, label %left, label %join

left:
  call void @unknown(i32 %x)
  %cmp = icmp eq i32 %x, %y
  br i1 %cmp, label %right, label %right

right:
  call void @unknown(i32 %y)
  switch i32 %y, label %join [
  i32 0, label %join
  i32 1, label %join
  ]

join:
  %r = phi i32 [ %x, %entry ], [ %y, %right ], [ %y, %right ], [ %y, %right ]
  ret i32 %r
}

; %fwd only jumps to %join: it is removed, %then branches to %join directly,
; and the PHI entry for %fwd moves to %then. %fwd.conflict is kept: its
; predecessor %else also branches to %join directly, and the PHI needs a
; different value on each of the two paths, which a single edge from %else
; could not provide.
define i32 @forwarding_blocks_and_phis(i1 %c, i1 %d) {
; CHECK-LABEL: define i32 @forwarding_blocks_and_phis(
; CHECK-SAME: i1 [[C:%.*]], i1 [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    call void @unknown(i32 1)
; CHECK-NEXT:    br label %[[JOIN:.*]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    call void @unknown(i32 2)
; CHECK-NEXT:    br i1 [[D]], label %[[FWD_CONFLICT:.*]], label %[[JOIN]]
; CHECK:       [[FWD_CONFLICT]]:
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[R:%.*]] = phi i32 [ 3, %[[FWD_CONFLICT]] ], [ 2, %[[ELSE]] ], [ 1, %[[THEN]] ]
; CHECK-NEXT:    ret i32 [[R]]
;
entry:
  br i1 %c, label %then, label %else

then:
  call void @unknown(i32 1)
  br label %fwd

fwd:
  br label %join

else:
  call void @unknown(i32 2)
  br i1 %d, label %fwd.conflict, label %join

fwd.conflict:
  br label %join

join:
  %r = phi i32 [ 1, %fwd ], [ 2, %else ], [ 3, %fwd.conflict ]
  ret i32 %r
}

; Blocks that cannot be reached from the entry block are removed, including
; unreachable loops and the side effects in them, which can never execute. The
; PHI in %exit loses its entry for %dead.loop and is replaced by %x; %exit is
; then merged into %entry.
define i32 @unreachable_blocks(i32 %x, ptr %p) {
; CHECK-LABEL: define i32 @unreachable_blocks(
; CHECK-SAME: i32 [[X:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret i32 [[X]]
;
entry:
  br label %exit

dead:
  store i32 %x, ptr %p
  br label %dead.loop

dead.loop:
  %i = phi i32 [ 0, %dead ], [ %i.next, %dead.loop ]
  %i.next = add i32 %i, 1
  %cmp = icmp eq i32 %i.next, %x
  br i1 %cmp, label %exit, label %dead.loop

exit:
  %r = phi i32 [ %x, %entry ], [ %i.next, %dead.loop ]
  ret i32 %r
}

; %spin only jumps to itself. It is an infinite loop, which is observable
; behavior, so it is kept.
define void @infinite_loop(i1 %c) {
; CHECK-LABEL: define void @infinite_loop(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C]], label %[[SPIN:.*]], label %[[EXIT:.*]]
; CHECK:       [[SPIN]]:
; CHECK-NEXT:    br label %[[SPIN]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br i1 %c, label %spin, label %exit

spin:
  br label %spin

exit:
  ret void
}

;===----------------------------------------------------------------------===;
; 3. Dead stack slot (alloca) elimination
;===----------------------------------------------------------------------===;

; %x is never read and its address does not escape, so the store and the alloca
; are removed.
define dso_local i32 @dead_stack_slot(i32 %argc, ptr %argv) {
; CHECK-LABEL: define dso_local i32 @dead_stack_slot(
; CHECK-SAME: i32 [[ARGC:%.*]], ptr [[ARGV:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret i32 0
;
entry:
  %x = alloca i32
  store i32 10, ptr %x
  ret i32 0
}

; Every write to %s is removed with it: a store, writes through a GEP by memset
; and memcpy, and the lifetime markers. The load from %s is dead, so it does not
; count as a read. Once the store is gone, the computation of the stored value
; %v is dead as well.
define void @stack_slot_writes(i32 %n, ptr %src) {
; CHECK-LABEL: define void @stack_slot_writes(
; CHECK-SAME: i32 [[N:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret void
;
entry:
  %s = alloca { i32, [8 x i8] }
  call void @llvm.lifetime.start.p0(ptr %s)
  %v = call i32 @pure(i32 %n)
  store i32 %v, ptr %s
  %arr = getelementptr inbounds { i32, [8 x i8] }, ptr %s, i64 0, i32 1
  call void @llvm.memset.p0.i64(ptr %arr, i8 0, i64 8, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %arr, ptr %src, i64 8, i1 false)
  %dead.load = load i32, ptr %s
  call void @llvm.lifetime.end.p0(ptr %s)
  ret void
}

; Stack slots are kept, together with their writes, if they are read (%read),
; if their address escapes (%escapes), if they are accessed with a volatile
; store (%volatile), or if they are the source of a memcpy (%copied).
define i32 @live_stack_slots(i32 %n, ptr %dst) {
; CHECK-LABEL: define i32 @live_stack_slots(
; CHECK-SAME: i32 [[N:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[READ:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[ESCAPES:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[VOLATILE:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[COPIED:%.*]] = alloca i32, align 4
; CHECK-NEXT:    store i32 [[N]], ptr [[READ]], align 4
; CHECK-NEXT:    store i32 [[N]], ptr [[ESCAPES]], align 4
; CHECK-NEXT:    call void @use(ptr [[ESCAPES]])
; CHECK-NEXT:    store volatile i32 [[N]], ptr [[VOLATILE]], align 4
; CHECK-NEXT:    store i32 [[N]], ptr [[COPIED]], align 4
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr [[DST]], ptr [[COPIED]], i64 4, i1 false)
; CHECK-NEXT:    [[R:%.*]] = load i32, ptr [[READ]], align 4
; CHECK-NEXT:    ret i32 [[R]]
;
entry:
  %read = alloca i32
  %escapes = alloca i32
  %volatile = alloca i32
  %copied = alloca i32
  store i32 %n, ptr %read
  store i32 %n, ptr %escapes
  call void @use(ptr %escapes)
  store volatile i32 %n, ptr %volatile
  store i32 %n, ptr %copied
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %copied, i64 4, i1 false)
  %r = load i32, ptr %read
  ret i32 %r
}

; The address of %a is stored in %pa, which is read, so %a can be read through
; the loaded pointer and is kept. The address of %b is stored in %pb, which is
; never read, so both %b and %pb are removed. %node stores its own address,
; which nothing can read either.
define i32 @address_stored_in_stack_slot(i32 %n) {
; CHECK-LABEL: define i32 @address_stored_in_stack_slot(
; CHECK-SAME: i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[PA:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store i32 [[N]], ptr [[A]], align 4
; CHECK-NEXT:    store ptr [[A]], ptr [[PA]], align 8
; CHECK-NEXT:    [[P:%.*]] = load ptr, ptr [[PA]], align 8
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    ret i32 [[V]]
;
entry:
  %a = alloca i32
  %pa = alloca ptr
  store i32 %n, ptr %a
  store ptr %a, ptr %pa
  %b = alloca i32
  %pb = alloca ptr
  store i32 %n, ptr %b
  store ptr %b, ptr %pb
  %node = alloca { ptr, i32 }
  store ptr %node, ptr %node
  %p = load ptr, ptr %pa
  %v = load i32, ptr %p
  ret i32 %v
}

; A variable that lived in a removed stack slot is described by the values
; stored to it instead: the #dbg_declare becomes a #dbg_value at the store.
define i32 @dead_stack_slot_debug_info(i32 %n) !dbg !14 {
; CHECK-LABEL: define i32 @dead_stack_slot_debug_info(
; CHECK-SAME: i32 [[N:%.*]]) !dbg [[DBG14:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:      #dbg_value(i32 [[N]], [[META16:![0-9]+]], !DIExpression(), [[META17:![0-9]+]])
; CHECK-NEXT:    ret i32 0, !dbg [[DBG18:![0-9]+]]
;
entry:
  %x = alloca i32, !dbg !16
    #dbg_declare(ptr %x, !15, !DIExpression(), !16)
  store i32 %n, ptr %x, !dbg !16
  ret i32 0, !dbg !17
}

; Typical unoptimized code for "if (c) x = x + 1; return x0;" where x is a
; local variable that is never read: removing the dead stack slot empties
; %then, which is then removed by dead block elimination together with the
; branch, leaving a single block.
define i32 @dead_stack_slot_and_blocks(i1 %c, i32 %x) {
; CHECK-LABEL: define i32 @dead_stack_slot_and_blocks(
; CHECK-SAME: i1 [[C:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret i32 [[X]]
;
entry:
  %x.addr = alloca i32
  store i32 %x, ptr %x.addr
  br i1 %c, label %then, label %end

then:
  %inc = add i32 %x, 1
  store i32 %inc, ptr %x.addr
  br label %end

end:
  ret i32 %x
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3, !4}

!0 = distinct !DICompileUnit(language: DW_LANG_C99, file: !1, producer: "test", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug)
!1 = !DIFile(filename: "simple-dce.c", directory: "/")
!2 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = !{i32 7, !"Dwarf Version", i32 5}
!5 = distinct !DISubprogram(name: "debug_info_salvage", scope: !1, file: !1, line: 1, type: !6, scopeLine: 1, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !8)
!6 = !DISubroutineType(types: !7)
!7 = !{!2, !2}
!8 = !{!9, !10}
!9 = !DILocalVariable(name: "a", scope: !5, file: !1, line: 2, type: !2)
!10 = !DILocalVariable(name: "b", scope: !5, file: !1, line: 3, type: !2)
!11 = !DILocation(line: 2, column: 1, scope: !5)
!12 = !DILocation(line: 3, column: 1, scope: !5)
!13 = !DILocation(line: 4, column: 1, scope: !5)
!14 = distinct !DISubprogram(name: "dead_stack_slot_debug_info", scope: !1, file: !1, line: 10, type: !6, scopeLine: 10, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !18)
!15 = !DILocalVariable(name: "x", scope: !14, file: !1, line: 11, type: !2)
!16 = !DILocation(line: 11, column: 1, scope: !14)
!17 = !DILocation(line: 12, column: 1, scope: !14)
!18 = !{!15}
