; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --version 6
; Tests for the SimpleDCE pass (-passes=simple-dce). Each section covers one
; of the transformations described in DCE-Doc.md.
;
; RUN: opt -passes=simple-dce -S < %s | FileCheck %s
; Running the pass a second time must not change anything.
; RUN: opt -passes=simple-dce,simple-dce -S < %s | FileCheck %s

declare void @unknown(i32)
declare void @use(ptr)
declare i32 @pure(i32) memory(none) nounwind willreturn
declare i32 @may_not_return(i32) memory(none) nounwind

;===----------------------------------------------------------------------===;
; 1. Trivially dead instruction elimination
;===----------------------------------------------------------------------===;

; Example 1 from the requirements. %add only becomes unused once %mul is
; removed; both are removed in one run.
define dso_local i32 @dead_instructions(i32 %argc, ptr %argv) {
; CHECK-LABEL: define dso_local i32 @dead_instructions(
; CHECK-SAME: i32 [[ARGC:%.*]], ptr [[ARGV:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret i32 0
;
entry:
  %add = add nsw i32 %argc, 42
  %mul = mul nsw i32 %add, 2
  ret i32 0
}

; Instructions with side effects are kept even though their results are
; unused, and so is everything that computes their operands: memory writes,
; volatile and atomic accesses, calls to unknown functions, and calls that do
; not touch memory but may not return.
define void @side_effects_are_kept(ptr %p, i32 %x) {
; CHECK-LABEL: define void @side_effects_are_kept(
; CHECK-SAME: ptr [[P:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V:%.*]] = add i32 [[X]], 1
; CHECK-NEXT:    store i32 [[V]], ptr [[P]], align 4
; CHECK-NEXT:    [[VOL:%.*]] = load volatile i32, ptr [[P]], align 4
; CHECK-NEXT:    [[RMW:%.*]] = atomicrmw add ptr [[P]], i32 1 seq_cst, align 4
; CHECK-NEXT:    call void @unknown(i32 [[X]])
; CHECK-NEXT:    [[NR:%.*]] = call i32 @may_not_return(i32 [[X]])
; CHECK-NEXT:    ret void
;
entry:
  %v = add i32 %x, 1
  store i32 %v, ptr %p
  %vol = load volatile i32, ptr %p
  %rmw = atomicrmw add ptr %p, i32 1 seq_cst
  call void @unknown(i32 %x)
  %nr = call i32 @may_not_return(i32 %x)
  ret void
}

; Unused side-effect-free instructions are removed, including plain loads and
; calls to functions that neither write memory, nor unwind, nor fail to
; return. %keep is returned, so it and its operand %base stay.
define i32 @side_effect_free_are_removed(ptr %p, i32 %x, i32 %y) {
; CHECK-LABEL: define i32 @side_effect_free_are_removed(
; CHECK-SAME: ptr [[P:%.*]], i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[BASE:%.*]] = add i32 [[X]], [[Y]]
; CHECK-NEXT:    [[KEEP:%.*]] = mul i32 [[BASE]], 5
; CHECK-NEXT:    ret i32 [[KEEP]]
;
entry:
  %ld = load i32, ptr %p
  %c = call i32 @pure(i32 %ld)
  %base = add i32 %x, %y
  %keep = mul i32 %base, 5
  %dead = sub i32 %keep, %c
  ret i32 %keep
}

; %sum and %sum.next only use each other, so neither is ever unused, but
; nothing that has to be kept depends on them. The induction variable controls
; the loop exit and is kept.
define void @dead_phi_cycle(i32 %n) {
; CHECK-LABEL: define void @dead_phi_cycle(
; CHECK-SAME: i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %sum = phi i32 [ 0, %entry ], [ %sum.next, %loop ]
  %sum.next = add i32 %sum, %i
  %i.next = add i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Lifetime markers are removed together with an alloca that has no other
; users. For %dead this is only the case after the dead %gep is removed, which
; happens in the same run. The markers of %live, which escapes, are kept.
define void @lifetime_markers() {
; CHECK-LABEL: define void @lifetime_markers() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LIVE:%.*]] = alloca i32, align 4
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[LIVE]])
; CHECK-NEXT:    call void @use(ptr [[LIVE]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[LIVE]])
; CHECK-NEXT:    ret void
;
entry:
  %dead = alloca [4 x i32]
  call void @llvm.lifetime.start.p0(ptr %dead)
  %gep = getelementptr [4 x i32], ptr %dead, i64 0, i64 1
  call void @llvm.lifetime.end.p0(ptr %dead)
  %live = alloca i32
  call void @llvm.lifetime.start.p0(ptr %live)
  call void @use(ptr %live)
  call void @llvm.lifetime.end.p0(ptr %live)
  ret void
}

; Debug records of removed instructions are rewritten in terms of the remaining
; operands (salvaged). This works through several levels (%b uses %a), even
; though the block containing the use %b is laid out before the block
; containing its operand %a.
define i32 @debug_info_salvage(i32 %x) !dbg !5 {
; CHECK-LABEL: define i32 @debug_info_salvage(
; CHECK-SAME: i32 [[X:%.*]]) !dbg [[DBG4:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[DEF:.*]]
; CHECK:       [[USE:.*]]:
; CHECK-NEXT:      #dbg_value(i32 [[X]], [[META10:![0-9]+]], !DIExpression(DW_OP_plus_uconst, 1, DW_OP_constu, 3, DW_OP_mul, DW_OP_stack_value), [[META11:![0-9]+]])
; CHECK-NEXT:    ret i32 [[X]], !dbg [[DBG12:![0-9]+]]
; CHECK:       [[DEF]]:
; CHECK-NEXT:      #dbg_value(i32 [[X]], [[META9:![0-9]+]], !DIExpression(DW_OP_plus_uconst, 1, DW_OP_stack_value), [[META13:![0-9]+]])
; CHECK-NEXT:    br label %[[USE]]
;
entry:
  br label %def

use:
  %b = mul i32 %a, 3, !dbg !12
    #dbg_value(i32 %b, !10, !DIExpression(), !12)
  ret i32 %x, !dbg !13

def:
  %a = add i32 %x, 1, !dbg !11
    #dbg_value(i32 %a, !9, !DIExpression(), !11)
  br label %use
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3, !4}

!0 = distinct !DICompileUnit(language: DW_LANG_C99, file: !1, producer: "test", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug)
!1 = !DIFile(filename: "simple-dce.c", directory: "/")
!2 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = !{i32 7, !"Dwarf Version", i32 5}
!5 = distinct !DISubprogram(name: "debug_info_salvage", scope: !1, file: !1, line: 1, type: !6, scopeLine: 1, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !8)
!6 = !DISubroutineType(types: !7)
!7 = !{!2, !2}
!8 = !{!9, !10}
!9 = !DILocalVariable(name: "a", scope: !5, file: !1, line: 2, type: !2)
!10 = !DILocalVariable(name: "b", scope: !5, file: !1, line: 3, type: !2)
!11 = !DILocation(line: 2, column: 1, scope: !5)
!12 = !DILocation(line: 3, column: 1, scope: !5)
!13 = !DILocation(line: 4, column: 1, scope: !5)
